{
  "formatVersion": "1.1",
  "component": {
    "group": "com.daiji110.androidfirstsdk",
    "module": "androidfirstsdk",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "androidfirstsdk-1.0.aar",
          "url": "androidfirstsdk-1.0.aar",
          "size": 4384,
          "sha512": "243f2c6a3c83ed992d8764c1beae3074eb4282ec814828cc0bfea751c32ecd9d484dffe2f75264e63518cedd01349214a44f5a2b4af8c3aedd1829c4d17e740f",
          "sha256": "98fa9f66d03e0673274258efcbdb2cf7d3df1f9f37019e47ffc1fb711ad9e7ba",
          "sha1": "54d102f24e93d17c55883f0815642fcd991ce62a",
          "md5": "e48228adbc4253a0e41c50609e6aa452"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "androidfirstsdk-1.0.aar",
          "url": "androidfirstsdk-1.0.aar",
          "size": 4384,
          "sha512": "243f2c6a3c83ed992d8764c1beae3074eb4282ec814828cc0bfea751c32ecd9d484dffe2f75264e63518cedd01349214a44f5a2b4af8c3aedd1829c4d17e740f",
          "sha256": "98fa9f66d03e0673274258efcbdb2cf7d3df1f9f37019e47ffc1fb711ad9e7ba",
          "sha1": "54d102f24e93d17c55883f0815642fcd991ce62a",
          "md5": "e48228adbc4253a0e41c50609e6aa452"
        }
      ]
    }
  ]
}
